#!/bin/bash
HOME_ENV="${HOME}/.envrc"
touch "${HOME_ENV}"
HOME_BIN="${HOME}/bin"
mkdir -p "${HOME_BIN}"
EDITOR="code --wait"
GOPATH="${HOME}/go"
GOBIN="${GOPATH}/bin"
KUBE_EDITOR="${EDITOR}"
PATH="${HOME_BIN}:${GOBIN}:${PATH}"
echo "export HOME_ENV=$HOME_ENV" >> "${HOME_ENV}"
echo "export HOME_BIN=$HOME_BIN" >> "${HOME_ENV}"
echo "export EDITOR=$EDITOR" >> "${HOME_ENV}"
echo "export GOPATH=$GOPATH" >> "${HOME_ENV}"
echo "export GOBIN=$GOBIN" >> "${HOME_ENV}"
echo "export KUBE_EDITOR=$KUBE_EDITOR" >> "${HOME_ENV}"
echo "export PATH=$PATH" >> "${HOME_ENV}"
