#!/bin/bash
export OS="darwin"
export ARCH="amd64"
export HOME_LOCAL_BIN="${HOME}/.local/bin"
export PATH="${HOME_LOCAL_BIN}:${PATH}"
export EDITOR="code --editor"
export GITHUB_NAME="Alexander Lerma"
export GITHUB_EMAIL="alexander.lerma@neuralnetes.com"
export GITHUB_BASE_WORKSPACE="${GITHUB_WORKSPACE}/workspace/base"
bash "${GITHUB_BASE_WORKSPACE}/generate.sh"
source "${GITHUB_BASE_WORKSPACE}/generate.sh"